drop table stored_pokemon;

create table stored_pokemon(
id serial primary key,
pokedex_id integer references pokemon(id),
name varchar(100) NOT NULL,
trainer_name varchar(100) NOT NULL,
team_name varchar(100) NOT NULL,
date_modified timestamp default current_timestamp,
type varchar(30) NOT NULL,
level integer NOT NULL,
hp integer NOT NULL,
attack integer NOT NULL,
defense integer NOT NULL,
sp_attack integer NOT NULL,
sp_defense integer NOT NULL,
speed integer NOT NULL,
nature varchar(30) NOT NULL,
ability varchar(30) NOT NULL,
iv_0 integer NOT NULL,
iv_1 integer NOT NULL,
iv_2 integer NOT NULL,
iv_3 integer NOT NULL,
iv_4 integer NOT NULL,
iv_5 integer NOT NULL,
move_1 varchar(30),
move_2 varchar(30),
move_3 varchar(30),
move_4 varchar(30));